// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const normalizeDatabaseUrl = (url: string | undefined): string => {
  const value = (url || "").trim();

  return value
    .replace(/^DATABASE_URL=/, "")
    .replace(/^['"]|['"]$/g, "");
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: normalizeDatabaseUrl(process.env["DATABASE_URL"]) || "postgresql://user:password@localhost:5432/app",
  },
});
